version: "3.9"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./openapi:/openapi
    ports:
      - "8000:8000"
    environment:
      - OPENAPI_SPEC_PATH=/openapi/openapi.yml
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - ./openapi:/openapi
    ports:
      - "3050:3000"
    environment:
      - OPENAPI_SPEC_PATH=/openapi/openapi.yml
    command: sh -c "npm install && npm run dev"
