openapi: 3.0.3
info:
  title: Beispiel API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Sag Hallo
      responses:
        "200":
          description: Erfolgreich
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
